# Generated by Django 5.1.6 on 2025-02-22 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0002_remove_product_image_remove_product_colour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
